apiVersion: skaffold/v4beta14
kind: Config
manifests:
  rawYaml:
    - infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: thelastofuslinco/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.ts"
            dest: .
          - src: "**/*.tsx"
            dest: .
          - src: "**/*.css"
            dest: .

    - image: thelastofuslinco/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .

    - image: thelastofuslinco/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .

    - image: thelastofuslinco/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .

    - image: thelastofuslinco/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .

    - image: thelastofuslinco/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
